name: Running Code Coverage

on: [push]
jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - '1.21'

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - run: go test -v -coverprofile=profile.cov

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: profile.cov